### ISSUE TITLE
Lab 04

### ISSUE THREAD

**Issue by davidrleal** [Watts-College/paf-515-spr-2024#12]
Hi. I was going through my rmd document and when I arrived at the LIHTC K-Means section I got an error and am unsure how to fix it. Has anyone come across this issue? Thanks!

<img width="943" alt="Screenshot 2024-04-15 at 2 56 52 PM" src="https://github.com/Watts-College/paf-515-spr-2024/assets/122239486/abe5fa9f-dac7-48a7-aa53-f321f79551f9">

<img width="943" alt="Screenshot 2024-04-15 at 2 56 37 PM" src="https://github.com/Watts-College/paf-515-spr-2024/assets/122239486/9e97ef3f-eac2-435c-a809-33e4c0aa9f11">

**Comment by castower** [comment]
Hello @davidrleal,

The error is related to the row count in your data set.

You can update the elbow_plot function code to the following to account for a row count smaller than 15:

```
elbow_plot <- function(df) {
  
  # Code source: https://uc-r.github.io/kmeans_clustering
  
  # Repeats same outcome each time run
  set.seed(123)

  # function to compute total within-cluster sum of square 
  wss <- function(k) {
    print(k)
    kmeans(df, k, nstart = 10, iter.max=25  )$tot.withinss
  }
  
  # Compute and plot wss for k = 1 to k = 15 (or one less than nrow() if there's less than 15 rows in df)
  if (nrow(df) > 15) {
    k.values <- 1:15
    print(k.values)
  } else {
    end <- nrow(df)-1
    k.values <- 1:end
    print(k.values)
  }
  
  # extract wss for 2-15 (or one less than nrow(df) if there's less than 15 rows in df) clusters
  wss_values <- map_dbl(k.values, wss)
  
  plot(k.values, wss_values,
         type="b", pch = 19, frame = FALSE, 
         xlab="Number of clusters K",
         ylab="Total within-clusters sum of squares")  
}


```

**Comment by castower** [comment]
For future reference, the code has been updated on the course site. You may have to refresh/clear cache to see the update (or you can copy the code from above):

[https://r-class.github.io/paf-515-course-materials/labs/wk04/lab-04-middle-atlantic-division.html#k-means-clustering-1](https://r-class.github.io/paf-515-course-materials/labs/wk04/lab-04-middle-atlantic-division.html#k-means-clustering-1)

**Comment by davidrleal** [comment]
Great. Thank you! It works.
