### ISSUE TITLE
Lab 03 Function Error

### ISSUE THREAD

**Issue by JJSpaeth** [Watts-College/paf-515-spr-2024#8]
I've encountered an error while attempting to execute one of the functions in Lab 03. It seems there's an issue with svi_percentages10. Upon inspection, it appears that the error lies within the line referencing 'pct age 18-64'. I believe it should incorporate the '_10' suffixes instead of the '_20'. Whenever I try to execute the function, the following error message is displayed:

Error in `summarise()`:
ℹ In argument: `pct age 18-64 = round(...)`.
Caused by error:
! object 'E_TOTPOP_20' not found

After modifying the suffixes to '_10', the function was able to execute successfully.

Respectfully,
John Spaeth

`# Calculate SVI variable percentages ----

svi_percentages10 <- function(df, division_name) {
  df_out <- 
    df %>% 
    filter(!is.na(ET_INSURSTATUS_12)) %>%
    summarise(
      division = division_name,
      year = 2010,
      `pct in poverty` = round(sum(E_POV150_10)/sum(ET_POVSTATUS_10)*100),
      `pct not in poverty` = round(((sum(ET_POVSTATUS_10) - sum(E_POV150_10))/sum(ET_POVSTATUS_10))*100),
      `pct unemployed` = round(sum(E_UNEMP_10)/sum(ET_EMPSTATUS_10)*100),
      `pct employed` = round(((sum(ET_EMPSTATUS_10) - sum(E_UNEMP_10))/sum(ET_EMPSTATUS_10))*100),
      `pct housing cost-burdened` = round(sum(E_HBURD_10)/sum(ET_HOUSINGCOST_10)*100),
      `pct not housing cost-burdened` = round(((sum(ET_HOUSINGCOST_10) - sum(E_HBURD_10))/sum(ET_HOUSINGCOST_10))*100),
      `pct adults without high school diploma` = round(sum(E_NOHSDP_10)/sum(ET_EDSTATUS_10)*100),
      `pct adults with high school diploma` = round(((sum(ET_EDSTATUS_10) - sum(E_NOHSDP_10))/sum(ET_EDSTATUS_10))*100),
      `pct age 17 & under` = round(sum(E_AGE17_10)/sum(E_TOTPOP_10)*100),
      `pct age 18-64` = round( (sum(E_TOTPOP_20)/sum(E_TOTPOP_20)*100) - (sum(round(sum(E_AGE17_20)/sum(E_TOTPOP_20)*100), round(sum(E_AGE65_20)/sum(E_TOTPOP_20)*100)))),
      `pct age 65+` = round(sum(E_AGE65_10)/sum(E_TOTPOP_10)*100),
      `pct single parent families` = round(sum(E_SNGPNT_10)/sum(ET_FAMILIES_10)*100),
      `pct other families` = round(((sum(ET_FAMILIES_10) - sum(E_SNGPNT_10))/sum(ET_FAMILIES_10))*100),
      `pct limited English speakers` = round(sum(E_LIMENG_10)/sum(ET_POPAGE5UP_10)*100),
      `pct proficient English speakers` = round(((sum(ET_POPAGE5UP_10) - sum(E_LIMENG_10))/sum(ET_POPAGE5UP_10))*100),
      `pct Minority race/ethnicity` = round(sum(E_MINRTY_10)/sum(ET_POPETHRACE_10)*100),
      `pct Non-Hispanic White race/ethnicity` = round(((sum(ET_POPETHRACE_10) - sum(E_MINRTY_10))/sum(ET_POPETHRACE_10))*100),
      `pct in multi-unit housing` = round(sum(E_MUNIT_10)/sum(E_STRHU_10)*100),
      `pct in mobile housing` = round(sum(E_MOBILE_10)/sum(E_STRHU_10)*100),
      `pct in other housing` = (100 - sum(round(sum(E_MUNIT_10)/sum(E_STRHU_10)*100), round(sum(E_MOBILE_10)/sum(E_STRHU_10)*100))),
      `pct in crowded living spaces` = round(sum(E_CROWD_10)/sum(ET_OCCUPANTS_10)*100),
      `pct in non-crowded living spaces` = round(((sum(ET_OCCUPANTS_10) - sum(E_CROWD_10))/sum(ET_OCCUPANTS_10))*100),
      `pct with no vehicle access` = round(sum(E_NOVEH_10)/sum(ET_KNOWNVEH_10)*100),
      `pct with vehicle access` = round(((sum(ET_KNOWNVEH_10) - sum(E_NOVEH_10))/sum(ET_KNOWNVEH_10))*100),
      `pct in group living quarters` = round(sum(E_GROUPQ_10)/sum(ET_HHTYPE_10)*100),
      `pct not in group living quarters` = round(((sum(ET_HHTYPE_10) - sum(E_GROUPQ_10))/sum(ET_HHTYPE_10))*100),
      `pct without health insurance` = round(sum(E_UNINSUR_12)/sum(ET_INSURSTATUS_12)*100),
      `pct with health insurance` = round(((sum(ET_INSURSTATUS_12) - sum(E_UNINSUR_12))/sum(ET_INSURSTATUS_12))*100),
      `pct disabled civilians` = round(sum(E_DISABL_12)/sum(ET_DISABLSTATUS_12)*100),
      `pct not disabled civilians` = round(((sum(ET_DISABLSTATUS_12) - sum(E_DISABL_12))/sum(ET_DISABLSTATUS_12))*100)
    )
  return(df_out)
}

svi_percentages20 <- function(df, division_name) {
  df_out <-  df %>% 
    summarise(
      division = division_name,
      year = 2020,
      `pct in poverty` = round(sum(E_POV150_20)/sum(ET_POVSTATUS_20)*100),
      `pct not in poverty` = round(((sum(ET_POVSTATUS_20) - sum(E_POV150_20))/sum(ET_POVSTATUS_20))*100),
      `pct unemployed` = round(sum(E_UNEMP_20)/sum(ET_EMPSTATUS_20)*100),
      `pct employed` = round(((sum(ET_EMPSTATUS_20) - sum(E_UNEMP_20))/sum(ET_EMPSTATUS_20))*100),
      `pct housing cost-burdened` = round(sum(E_HBURD_20)/sum(ET_HOUSINGCOST_20)*100),
      `pct not housing cost-burdened` = round(((sum(ET_HOUSINGCOST_20) - sum(E_HBURD_20))/sum(ET_HOUSINGCOST_20))*100),
      `pct adults without high school diploma` = round(sum(E_NOHSDP_20)/sum(ET_EDSTATUS_20)*100),
      `pct adults with high school diploma` = round(((sum(ET_EDSTATUS_20) - sum(E_NOHSDP_20))/sum(ET_EDSTATUS_20))*100),
      `pct age 17 & under` = round(sum(E_AGE17_20)/sum(E_TOTPOP_20)*100),
      `pct age 18-64` = round( (sum(E_TOTPOP_20)/sum(E_TOTPOP_20)*100) - (sum(round(sum(E_AGE17_20)/sum(E_TOTPOP_20)*100), round(sum(E_AGE65_20)/sum(E_TOTPOP_20)*100)))),
      `pct age 65+` = round(sum(E_AGE65_20)/sum(E_TOTPOP_20)*100),
      `pct single parent families` = round(sum(E_SNGPNT_20)/sum(ET_FAMILIES_20)*100),
      `pct other families` = round(((sum(ET_FAMILIES_20) - sum(E_SNGPNT_20))/sum(ET_FAMILIES_20))*100),
      `pct limited English speakers` = round(sum(E_LIMENG_20)/sum(ET_POPAGE5UP_20)*100),
      `pct proficient English speakers` = round(((sum(ET_POPAGE5UP_20) - sum(E_LIMENG_20))/sum(ET_POPAGE5UP_20))*100),
      `pct Minority race/ethnicity` = round(sum(E_MINRTY_20)/sum(ET_POPETHRACE_20)*100),
      `pct Non-Hispanic White race/ethnicity` = round(((sum(ET_POPETHRACE_20) - sum(E_MINRTY_20))/sum(ET_POPETHRACE_20))*100),
      `pct in multi-unit housing` = round(sum(E_MUNIT_20)/sum(E_STRHU_20)*100),
      `pct in mobile housing` = round(sum(E_MOBILE_20)/sum(E_STRHU_20)*100),
      `pct in other housing` = (100 - sum(round(sum(E_MUNIT_20)/sum(E_STRHU_20)*100), round(sum(E_MOBILE_20)/sum(E_STRHU_20)*100))),
      `pct in crowded living spaces` = round(sum(E_CROWD_20)/sum(ET_OCCUPANTS_20)*100),
      `pct in non-crowded living spaces` = round(((sum(ET_OCCUPANTS_20) - sum(E_CROWD_20))/sum(ET_OCCUPANTS_20))*100),
      `pct with no vehicle access` = round(sum(E_NOVEH_20)/sum(ET_KNOWNVEH_20)*100),
      `pct with vehicle access` = round(((sum(ET_KNOWNVEH_20) - sum(E_NOVEH_20))/sum(ET_KNOWNVEH_20))*100),
      `pct in group living quarters` = round(sum(E_GROUPQ_20)/sum(ET_HHTYPE_20)*100),
      `pct not in group living quarters` = round(((sum(ET_HHTYPE_20) - sum(E_GROUPQ_20))/sum(ET_HHTYPE_20))*100),
      `pct without health insurance` = round(sum(E_UNINSUR_20)/sum(ET_INSURSTATUS_20)*100),
      `pct with health insurance` = round(((sum(ET_INSURSTATUS_20) - sum(E_UNINSUR_20))/sum(ET_INSURSTATUS_20))*100),
      `pct disabled civilians` = round(sum(E_DISABL_20)/sum(ET_DISABLSTATUS_20)*100),
      `pct not disabled civilians` = round(((sum(ET_DISABLSTATUS_20) - sum(E_DISABL_20))/sum(ET_DISABLSTATUS_20))*100)
    )
  return(df_out)
}`

**Comment by castower** [comment]
Hello @JJSpaeth,
Thanks for catching that! You're correct, it should have the _10 suffix. I updated the code earlier to account for rounding and accidentally typed 20 for both functions. I'll update it on the course website.
