### ISSUE TITLE
Lab03- Patchwork error

### ISSUE THREAD

**Issue by acampbell7** [Watts-College/paf-515-spr-2024#9]
Hi Professor,

As I just got the SF file to work on the Mac, now I got a new error, and I'm not sure if it's connected to the fix of the renv to work.

When I run any of the patchwork files, I get this error (this happened for all code chunks):

Error in Ops.data.frame(guide_loc, panel_loc) : 
  ‘==’ only defined for equally-sized data frames

I did check all attributes of pov, unemploy, house_cost, hsed, & healthins and they all have the list length of 11. 

I checked Slackoverflow, not much came up with this error
 
I, also, commented it out and the rest of the code worked (But I know that cannot be correct) 

Any guidance would be great, thanks!

**Comment by castower** [comment]
Hello @acampbell7,

Do you know if you have the latest versions of ggplot2 and patchwork installed? Looks like there have been issues with some versions of the packages conflicting and throwing this error:

See the following links:

- https://github.com/satijalab/seurat/issues/8170
- https://github.com/thomasp85/patchwork/issues/342

**Comment by acampbell7** [comment]
Thank you! Thank worked :)
